// <auto-generated />
namespace Dimmer_Labels_Wizard_WPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedColorDictionaries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedColorDictionaries));
        
        string IMigrationMetadata.Id
        {
            get { return "201604300837348_AddedColorDictionaries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
